### ISSUE TITLE
[NOT CONFIRMED] Adding the functionality to change between a set of different colour schemes

### ISSUE THREAD

**Issue by Edward-Nivison** [mazfil/lab-allocator#106]
Add the functionality to change the colour scheme using some setting to allow users to change how the product looks. Perhaps things like light or dark mode, high contrast, or just different colour schemes to customise for the user's preference.

**Comment by mazfil** [comment]
Closing for now as this isn't something in the current scope.
We can return and discuss this but this is only adding to confusion of issues and creating things that are not a priority.
