### ISSUE TITLE
Error uploading course data when lecture time specified

### ISSUE THREAD

**Issue by mazfil** [mazfil/lab-allocator#109]
When a lecture is specified and scheduled (**Prior to requested tutorial times**), an error is flagged.
See image below:

![image](https://github.com/user-attachments/assets/a31fea5b-7aae-4bb2-86ab-7d409e7bc3a1)

**Comment by matthewcawley02** [comment]
FIxed in https://github.com/mazfil/lab-allocator/commit/4b9e06006b83e478c1f6e84fd3d3aeac8aec4ed0
