### ISSUE TITLE
Courses should not be duplicated in manage data

### ISSUE THREAD

**Issue by mazfil** [mazfil/lab-allocator#111]
Only one record should be included in the data per course.
Tutorial time ranges should not be separated, not in scope.

Days and a time range for selected days should be specified.

**Comment by matthewcawley02** [comment]
Going to make it so for the Add Course/Save Course Data buttons, one is greyed out depending on what the user has typed into the Course Code field

Are the latter two dotpoints the input fields? Just asking cause if so then they've been finished since this issue was posted
