### ISSUE TITLE
Teamwork contribution regarding feedback from the audit.

### ISSUE THREAD

**Issue by Edward-Nivison** [mazfil/lab-allocator#116]
_I didn't find specific project task division or other content related to team work. But according to the audit pre 2, their teamwork should be good._

That is a fair point to bring up. I forgot that we should be showing that more clearly. What we have for that is the assigning of issues and our own "we know who is doing what" kind of attitude, but that should be done more clearly and show what each team members role is, and what they are currently working on. Thanks for the feedback!

_Originally posted by @Edward-Nivison in https://github.com/mazfil/lab-allocator/issues/92#issuecomment-2332971299_

**Comment by Edward-Nivison** [comment]
We should work on developing something to show the team member contribution on the landing page most importantly, and possibly some supporting documentation to show where we show contribution, and how you can find analytics, what issues are assigned to who, and stuff like that.

**Comment by RachelCaoCC** [comment]
Do we want another section in meeting minutes states contribution?

**Comment by Edward-Nivison** [comment]
That could possibly be a solution

Another would be to create a guide and links and where to find what we have been working on. The current working state (e.g. in the dev branch), and we should be assigning ourselves to issues more often.

**Comment by Edward-Nivison** [comment]
Added to README about different ways to see team member contribution. Closing now
