### ISSUE TITLE
SOW Acceptance

### ISSUE THREAD

**Issue by mazfil** [mazfil/lab-allocator#17]
Since the SoW represents the commitment, it is important that all team members and the client sign the SOW, after which it should not be changed (See comment under Document Version).

**Comment by RachelCaoCC** [comment]
> I don't think I have been fully updated on this so far, is the statement of work complete, signed and ready to be uploaded to GitHub? @mazfil @RachelCaoCC ?

I sent the revised pdf to Belinda but didn't get response yet

**Comment by Edward-Nivison** [comment]
It has been signed now!
