### ISSUE TITLE
project deliverables and planning

### ISSUE THREAD

**Issue by RachelCaoCC** [mazfil/lab-allocator#26]

**Comment by Edward-Nivison** [comment]
I was wondering if this could be made into a table so it is not taking up a lot of space?

**Comment by RachelCaoCC** [comment]
> I was wondering if this could be made into a table so it is not taking up a lot of space?

ok ill revise it now

**Comment by RachelCaoCC** [comment]
how about now?

**Comment by Edward-Nivison** [comment]
yeah that is good!
