### ISSUE TITLE
Design of the backend algorithm

### ISSUE THREAD

**Issue by alexdboxall** [mazfil/lab-allocator#31]
We should start planning how the backend algorithm is going to work - our current project deliverables schedule shows that this will be happening throughout weeks 3 and 4, and it is now week 3.

I will soon create a document (and put it in the /docs folder and link it here) outlining some of the different strategies we could use (e.g. brute force, genetic algorithms) and explain why they might / mightn't work. After that we should discuss what we'll go for, and then we can start designing/implementing it with a small amount of data to test its feasibility.

And anyone is free to contribute to this if they want to!

**Comment by Edward-Nivison** [comment]
Certainly. I will be happy to help with the research and we can get a discussion going with our next team meeting.

**Comment by alexdboxall** [comment]
Discussing it at the meeting sounds good - and I've thrown up some notes here: docs/notes/backend-algorithm-notes.md on why brute force won't work and how we could implement a GA to solve the problem.

**Comment by alexdboxall** [comment]
I've added some basic code implementing the general framework of a generic algorithm - we will mostly need to fill in Schedule.java with our project's solution. We'll also need to think about how we'll connect it to the frontend, and how it's receiving and storing data.

I should probably have made a pull request for this change - I will do this for all further code changes that I do.

**Comment by alexdboxall** [comment]
The backend can now generate random schedules. A pull request will be made and it will go in to the dev branch. After that, further work will be split up into other tasks.

![Image](https://github.com/mazfil/lab-allocator/assets/21270599/310b3223-0dc4-4a47-9400-39ac3453bdc6)

**Comment by alexdboxall** [comment]
Will close this issue now that #48 is merged - further backend changes will be done through new issues.
