### ISSUE TITLE
User Interface Design

### ISSUE THREAD

**Issue by mazfil** [mazfil/lab-allocator#32]
Prototype will be designed through figma.

**Comment by Edward-Nivison** [comment]
Was just testing something out

**Comment by mazfil** [comment]
Prior to completing the design ill need to do a bit of research into exactly who uses this, ill likely be conducting interviews / questionnaire with the SoCo admin team if possible.

**Comment by Edward-Nivison** [comment]
If this issue is completed, give a detailed description of what has been done, or if it has been referenced or repeated somewhere else reference the issue and close this, so it is closed.

**Comment by Edward-Nivison** [comment]
Need to bump this.

**Comment by mazfil** [comment]
Closing as this was replaced by the development issues of the frontend. Our figma prototype has already been finalised.
