### ISSUE TITLE
Implement a way of loading in global data about classes

### ISSUE THREAD

**Issue by alexdboxall** [mazfil/lab-allocator#36]
The system will need a global table of data about classes, e.g. the number of labs they have, the length of the tutorials, when the lecture is on, their name, etc.

A method should be implemented to load this from a file (created in #35) and into a global table that can be easily accessed throughout the backend. Classes should be accessible via an integer ID (e.g. COMP1100 = 0, COMP1110 = 1, etc.)

**Comment by Hexuan-Meng** [comment]
I think we will not be provided with the number of labs each course has, but only the number of enrolments according to our SOW. So, we may need to do some calculation to figure out how many labs each course should have based on the input data.

**Comment by alexdboxall** [comment]
In the notes I took in the first meeting I wrote that we didn't need to calculate the number of labs (this isn't recorded in the official meeting minutes though) - we can double check with Belinda today.

**Comment by alexdboxall** [comment]
Old issue from previous semester - a new issue will be created if necessary.
