### ISSUE TITLE
Fill in decision logs

### ISSUE THREAD

**Issue by alexdboxall** [mazfil/lab-allocator#37]
We've made decisions in most meetings, it would be good to document these separately to make it easier to see and reflect upon decisions we've made. It would also make it easier for Belinda to see our decisions and why we've made them.

I've put placeholder documents in the documentation folder - it would be great if they could be filled in with the decisions and justifications behind them from each meeting (the minutes will be helpful for this).

**Comment by Edward-Nivison** [comment]
I have created the decision log templates and we will make sure to fill out the decision logs from today's client meeting.

**Comment by Edward-Nivison** [comment]
I will fill out the current decisions over the current week and any future ones of relevance.

**Comment by Edward-Nivison** [comment]
Further decisions do not need an issue to show that they are being filled in but should be expected to be completed along side the meeting minutes.
