### ISSUE TITLE
Determine best host for Database

### ISSUE THREAD

**Issue by mazfil** [mazfil/lab-allocator#38]
So i think we've spoken about firebase.
Depending on how the algorithm runs we might also have to look at how we can store the data locally for the algorithm, however, thats up to those designing the backend.

**Comment by alexdboxall** [comment]
In terms of the backend, it will likely just download the database when it starts up and then convert it whatever objects it needs to for the algorithm.

**Comment by mazfil** [comment]
At the current time through development we will be using firebase. We will begin setting this up now.

**Comment by alexdboxall** [comment]
The host has been decided (Firebase) so this issue will be closed
