### ISSUE TITLE
Complete Project Charter

### ISSUE THREAD

**Issue by matthewcawley02** [mazfil/lab-allocator#39]

**Comment by Hexuan-Meng** [comment]
I put the link to the team charter under the statement of work on the landing page, according to the tutor's feedback. We all need to sign it if anyone has not.
<img width="509" alt="Screenshot 2024-08-12 150250" src="https://github.com/user-attachments/assets/bd2a1e38-5548-4ff9-a047-d62c1ee05d4c">
