### ISSUE TITLE
Having Code running on Server / VM

### ISSUE THREAD

**Issue by mazfil** [mazfil/lab-allocator#44]
Looking into options on how to have the front and backend running on a server.

**Comment by alexdboxall** [comment]
Over the next few weeks I will look into how we can get Spring Boot (or a similar framework) set up to serve both the backend and the frontend.

**Comment by alexdboxall** [comment]
In another repo I've set up Spring Boot to work with the backend - I will eventually create a new branch that has these changes but I'll probably wait for the branches to merge back into /dev first.

https://github.com/mazfil/lab-allocator/assets/21270599/0ce1180e-c035-4b9b-ae5b-04e44ab764a0
