### ISSUE TITLE
Write a fitness function

### ISSUE THREAD

**Issue by alexdboxall** [mazfil/lab-allocator#49]
`Scheduler.getFitness` needs to be implemented. This function should evaluate a schedule and assign it a score, the higher the score, the better the schedule. It must be deterministic - if the same schedule is passed into it, it should give the same value each time.

Some things to consider (not all of these need to be implemented):
- tutor workload (how many back-to-back tutorials?)
- gaps in the day for e.g. drop ins to happen, or for people to study (but not too many!)
- having classes spread throughout the week for variety (e.g. ideally on all days)
- having most classes during e.g. 10am-4pm
- having options for early and late classes for people who, e.g. might have commitments during the day
 - room utilisation (already taken care of in the 'freeSpace' variable)
- the number of labs of the same class that runs at the same time
     -> generally may want to minimise to increase options for students
     -> might *not* want to for really popular times though
- the number of other labs for other classes that run at that time (i.e. minimise clashes)
 - having back-to-back labs in the same room (e.g. to save tutors with back-to-back classes walking)
- convener preferences
- at least one room free in each time slot
- even utilisation of all rooms?

**Comment by matthewcawley02** [comment]
I've made a first version of the fitness function, now pushed to dev. For explanations, see https://github.com/mazfil/lab-allocator/blob/dev/docs/technical-reports/backend/fitness-function.md

**Comment by alexdboxall** [comment]
Your updated fitness function sometimes gives index out of bounds errors - I think you are sometimes mixing up room IDs and course IDs. I've commented those out for now so it still runs correctly, but you'll need to fix up those functions.

**Comment by alexdboxall** [comment]
Old issue from previous semester - a new issue will be created if necessary.
