### ISSUE TITLE
Identification of resources, risks, potential costs and who will bear them.

### ISSUE THREAD

**Issue by Edward-Nivison** [mazfil/lab-allocator#5]
Identify the resources that we all have (e.g., what devices everyone has, do they have access to a server already to host something, will we have to rent/buy a server to host it, etc.)

The potential risks of creating this product, could data be leaked in anyway, what are the risks if third-party API's are used, etc.

The potential costs and who will bear them. Depending on the product that we are trying to make, it could be that we need to rent/buy a server to host the brain (algorithm) or somewhere to store the database, or host the service we are providing. This could be free (use the ANU hosting service) or could cost if we find another solution. Anyone of the team can bear the cost, and up to $300 can be reimbursed by the COMP3500 budget.

**Comment by Hexuan-Meng** [comment]
I found that that on our landing page, there is a Project Resources(blank) section and a Project costs(with content from SOW) section, maybe we can only keep one of them since both of them are in the Resources and Costs section in our SOW.

**Comment by Edward-Nivison** [comment]
So I was looking at making the Project Resources page as the heading to reduce the amount of headings and making the Risk management and Project costs as sub-headings under that

Whats your thoughts?

**Comment by Edward-Nivison** [comment]
Completed
