### ISSUE TITLE
Lecture times

### ISSUE THREAD

**Issue by alexdboxall** [mazfil/lab-allocator#53]
Labs should not be scheduled at times which class with their own lecture.

There should be a way of checking if a lecture overlaps with a given lab time and length, and then the `Schedule.placeLabRandomly` method can be updated to exclude times which clash with lectures.

**Comment by Hexuan-Meng** [comment]
This issue is marked as closed as the `placeLabRandomly(Random rng, Course course)` in class `Schedule` will remove all times that overlap with the lectures of the given `course` by calling the `timesOverlapWithLectures()` method of class `Course`.
