### ISSUE TITLE
Implement Support Page

### ISSUE THREAD

**Issue by mazfil** [mazfil/lab-allocator#59]
See `src/frontend/src/pages/Support.js`

## Requirements
- [ ] Documentation.
- [ ] Quick User Guides.
- [ ] Potentially containing 'emergency' contact info in case of major faults.

**Comment by Edward-Nivison** [comment]
I am happy to have a go at making the support page, will work on it throughout the project course, and will likely keep it in a markdown file for easy reference from the Landing page (README.md) or start up the GitHub wiki to further have pages and easier to read "flows" in the support page.

**Comment by Edward-Nivison** [comment]
However I might move this to low priority as we haven't got a product for the consumer/client/end-user to use yet, so it is low on the agenda right now.

**Comment by Edward-Nivison** [comment]
Working on the about section in #55

**Comment by mazfil** [comment]
Closed - Issue remade for new sem.
