### ISSUE TITLE
Crossover has potential to throw exceptions if the crossover leads to a particularly bad arrangement of labs

### ISSUE THREAD

**Issue by alexdboxall** [mazfil/lab-allocator#63]
Following on from #61.

In the crossover operation, it is possible that the courses are laid out so badly that there is no longer any room for further labs to be placed randomly, which raises an exception and crashes the program.

My suggested idea to fix this is to catch any 'cannot place course' exceptions, and if one occurs, to just make the crossover return a completely random schedule instead. In very rare cases, it might need to retry a few if the random schedule also doesn't work. (Eventually random calls _will_ work, as we know that both parents exist, so there _are_ ways of generating valid schedules).

If after a few attempts at creating the entire randomly it still doesn't work, then we should print a warning (as it's looking like it's going to be very hard to do any scheduling), and then just return one of the two parents.

**Comment by Hexuan-Meng** [comment]
In the first generation, all the schedules are generated completely randomly, it also has the risk, which I believe is higher than the following generations, of throwing that exception.

**Comment by alexdboxall** [comment]
Yes there is a risk in the first generation - but that's why it throws an exception - if we can't generate an initial population then it's very unlikely there's going to be any way of allocating all of the labs. But that shouldn't happen - as the School of Computing isn't going to schedule more labs than they have room for. 

I suppose the initial population generation could get very unlucky and allocate badly enough that it throws the exception - we could always catch it and then just retry. If there's enough room for all the classes (and especially as SoCo aren't going to have every room fully booked), then random generation will eventually work.

**Comment by alexdboxall** [comment]
Old issue from previous semester - a new issue will be created if necessary.
