### ISSUE TITLE
Backend should upload results to Firebase

### ISSUE THREAD

**Issue by alexdboxall** [mazfil/lab-allocator#71]
The backend should be able to upload the results of a run to the database, so that the front end us able to read it and display it to the user.

There is a format in Firebase that should be used for the data format.

**Comment by mazfil** [comment]
If possible, could as much of the following be calculated by the backend and uploaded to firebase for each record, this will minimise the calculations required to display the data for the frontend when fetching the data:

RECORD NAME = "COMPXXXX_N" - where XXXX is the course code and N is the tutorial number
daysOfWeek: "n" - where n is an integer 1-5 corresponding to the day of the week.
startTime: "hh:mmss" - a string of the hour the tutorial starts
endTime: "hh:mm:ss" - a string of the hour the tutorial ends
location: "XXXX" - a string containing the tutorial location
course: "COMPXXXX" - a string comprising of the course code (XXXX) and the tutorial number N

**Comment by alexdboxall** [comment]
Yep all of that should be possible to be calculated on the backend

**Comment by alexdboxall** [comment]
PR #75

**Comment by Edward-Nivison** [comment]
Whats the progress on this, I have added an end date, if you are unhappy with this, please change it and comment your reasonings.

**Comment by alexdboxall** [comment]
This was completed yesterday, so I've just updated the end date to match.
