### ISSUE TITLE
Create an about page

### ISSUE THREAD

**Issue by mazfil** [mazfil/lab-allocator#79]
Continuation of old issue #55

Brief outline of the project, its purposes and information about the development team.

**Comment by mazfil** [comment]
https://github.com/mazfil/lab-allocator/issues/55#issuecomment-2084619224

**Comment by Edward-Nivison** [comment]
Filip has taught me how and where to write this out, so in the coming weeks and after user testing, I am planning on getting this done or at least started and implemented. Feedback and tips are always welcome!

**Comment by Edward-Nivison** [comment]
What do we think about this?

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Us - SoCo Lab Allocator</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <h1>About SoCo - Resource Maximisation Planning System for Labs</h1>
    </header>
    
    <section>
        <h2>Our Mission</h2>
        <p>At SoCo, our goal is to develop an adaptable resource allocation application for computer labs. The app intelligently schedules computing courses, maximizing the use of available resources while adhering to predefined constraints and restrictions.</p>
    </section>

    <section>
        <h2>Project Vision</h2>
        <p>The final product will adapt to new course entries and create the most efficient weekly layout of classes, ensuring optimal use of labs and resources within strict scheduling guidelines.</p>
    </section>

    <section>
        <h2>Meet the Team</h2>
        <p>We are a group of dedicated students working together to bring this solution to life. Meet our team <a href="https://github.com/mazfil/lab-allocator/blob/main/README.md#team-members-and-roles">here</a>.</p>
    </section>

    <section>
        <h2>Project Resources</h2>
        <p>We provide detailed documentation on our project, including technical constraints, stakeholder analysis, and development reports. Explore the full details on our <a href="https://github.com/mazfil/lab-allocator">GitHub repository</a>.</p>
    </section>
</body>
</html>`

It is rudimentary at the moment, but it could be a start for it.

![image](https://github.com/user-attachments/assets/a531a751-ece2-4b0c-8e6c-65551acf1f03)


@mazfil

**Comment by mazfil** [comment]
Looks great, we dont have to flesh out an extensive page. I think this is perfect for the purposes of the project.

**Comment by Edward-Nivison** [comment]
The about page is pretty much complete, I will work more on the styling of it later down the line, so I am going to extend the deadline for that to next week.
