### ISSUE TITLE
Rewrite database connection on backend

### ISSUE THREAD

**Issue by alexdboxall** [mazfil/lab-allocator#90]
Once the new database has been set up, we will need to modify the backend so that it communicates with that database instead of with Firebase.

Probably can't work on this until database has been chosen.

**Comment by Edward-Nivison** [comment]
@alexdboxall this is completed correct? The API is built and integrated for the backend. From my understanding of our last team meeting.

**Comment by alexdboxall** [comment]
Yes this is done
