### ISSUE TITLE
Reflection Logs

### ISSUE THREAD

**Issue by Edward-Nivison** [mazfil/lab-allocator#92]
Update the Reflection Logs with previous meetings reflections in the meeting minutes.

**Comment by Edward-Nivison** [comment]
_Currently, as the project is not finished (our project is something which needs to have at least a first version finished before use can come of it), the stakeholders are not yet getting value out of it in the sense of having a product. A major stakeholder is the client, who is beginning to see value based on first drafts of the product._ 

We are developing and planning on implementing a on-site solution to the client in the coming weeks. We have discussed with them about the opportunity of using a "test" lab computer as a temporary on-site machine to use it on as it would have the necessary development tools to run what what we have in the current state. However we would need to have sufficient documentation for it to be usable in that state.

We are in the works of setting up a server on campus which will likely be the final product.

Referencing relevant issues.
- #84 
- #79

**Comment by Edward-Nivison** [comment]
_It is good to see that you have recorded the time when the SoW was drafted. I can see that you are mostly following the structure of the SoW—well done! However, I cannot see your team charter explicitly. We are expecting it to be a separate document that has been signed by all team members._ 

We have a team charter that was created prior to the audit week, we have to get it signed and that is why it was not up on the github repository at the current time. It is unfortunate that we have missed this marking point for the audit, but it should be noted that we had it completed, just unsigned and not uploaded. We will improve on this in the future.

@matthewcawley02 

Referencing relevant issues:
- #39

**Comment by Edward-Nivison** [comment]
_Break down large tasks or deliverables into smaller, manageable tasks with clear deadlines. Assign these tasks to team members based on their expertise and availability._

Great feedback, we are in the works of doing this. I have detailed a thorough method of approach in the [Development Checklist](https://github.com/mazfil/lab-allocator?tab=readme-ov-file#handover-process--development-checklist). This details how issues shouldn't be too broad, how you should split things into more manageable issues that can be assigned appropriately. If there is anything wrong with the implmentation of this, feel free to comment on the relevant issue #85.

**Comment by Edward-Nivison** [comment]
_Whilst google sheets is a bit easier to use, i think if we are looking at keeping everything on github we should move the decision log to the markdown file on the repo._ 

We are still happy with using sheets, but with the introduction of the #92 issue and the ability to reference it whenever we make reflections it is showing there on github. The sheets is so it is easy to read and find things. It is also linked on github at [reflection log](https://github.com/mazfil/lab-allocator/blob/main/docs/reflection-log.md).

**Comment by Edward-Nivison** [comment]
_It is good to see that on the cover page of SoW, all team member's names are included. However, since the SoW represents the commitment, it is important that all team members and the client sign the SOW, after which it should not be changed. In your signed version of SoW, I can only see the client's signature in the Acceptance section, it is important for all team members to sign the document as well to show mutual agreement and commitment. _

We will be adding the signatures hopefully by today or by the end of this week. Thank you for noting this!

**Comment by Edward-Nivison** [comment]
_Communication with me as project lead has been great. There needs to be some additional resources and information provided so that we can do a wider consultation with other stakeholders and that has been timetabled._ 

This is crucial feedback that we need to action, we have been in talks with the client about this for a little while now and are in the process of doing something in the estimated timeframe of weeks 5 and 6. We have got to get some documentation up and going so we can do that. I will reference the relevant issues to this task, and relay to the team about this.

Relevant issues:
- #84 
- #79 
- #96

**Comment by Edward-Nivison** [comment]
_In your SoW, I can see clear signs of client engagement - good job! However, it is worth noting that tutors/examiners, your team members, and your shadow team are also key stakeholders, and their expectations need to be managed as well. It would be great if you could include them in your stakeholder analysis. Additionally, you mentioned that a server is expected from your client in the 'Resources and Costs' section. It would be helpful to specify when the server is required to ensure that both the client's and team members' expectations are managed._ 

We will make sure to add that to the relevant areas in the future. However since the project is designed for the sole purpose of making the lab allocation process simpler and faster for the School of Computing Team we are putting them as higher stakeholders over the tutors and shadow team. However the tutors and shadow team are valuable resources of feedback, they don't rank as high as the product that we need to deliver to our client.

Relevant issues:
- #97

**Comment by Edward-Nivison** [comment]
_Create a process for team members to give and receive feedback about communication practices_ 

I have detailed about this in issue #98, if there is anything that should be needed from me, let me know and I can work things out. If it is too personal there are other resources such as the tutors, the convenors, the cecc team, and anusa that you can reach out to.

We've got this team!

**Comment by Edward-Nivison** [comment]
_Our stakeholder engagement should be improved this semester over last semester, as we have organized a regular, weekly meeting time. We need to ensure we have an agenda set out ahead of time for these meetings to make the best use of our client's time._ 

I aim to add to the agenda prior to meetings each week so we have something to talk about. I encourage others to do the same and they can on their own accord do so. We have regular meetings on Mondays 9:00am-11:00am is our allocated time that we spend each week where we catch up, go over the agenda, and any other actionable items. We speak with the client midway through and update them on the progress, demo anything we can about the product and much more. I believe we are on the right track and are progressing steadily.

**Comment by Edward-Nivison** [comment]
### **UPDATE REFLECTION LOG STRUCTURE**

_Keep a record of key insights, lessons learned, and action items from each reflection session. Store these documents in a shared location accessible to the team_ 

There have been multiple comments with feedback on the reflection log about a change in the reflection structure, we will reflect on this and update the reflection log as needed. And make sure that we are properly showing what we have thought on and how we plan to action it.

**Comment by Edward-Nivison** [comment]
We have received some feedback from the audit on wednesday at 5:00pm about the colour schemes from our tutors, and our shadow team.

**The shadow team asked:**

> Will the user have the ability to select the colour scheme that they want to have?

Our answer to this is the colour scheme selection is not in scope as of the moment, but our main focus is providing something to the client that is easy to look at, and allows them to see more clearly what room is what, as the current way MyTimetable shows it, is not clear and very often confusing. So this is definitely a possibility if the client would see it as a useful addition, and we can work on it over the coming weeks and bring it up in the user testing. You can see the progress on this item in issue #106 .

**The tutors asked**

*Dian:*

> How did we come up with the colour schemes?

We came up with them using [coolors.co](https://coolors.co/). We then also modified the colour schemes, and implemented them into the code to test and verify that it worked.

*David*

> Have you thought about contrast or the ability for people to see it better?

So we have conducted some user testing with the client and the stakeholders that I our client has selected for us to provide tests for as they could possibly use it in the future. We have received feedback on the best suited one, but we could do further research into the different colour schemes we could use, what are the do's and don't's in the field.

*Liang*

> The landing page does not show the project output very clearly. You should look at adding some more to the landing page to show more about the progress that has been made this semester.

What we have at the moment is showing what we have majorly completed over the semester. However this does not always cover everything that has been done. For example, we have added changes to the fitness function in relation to client feedback to new criteria from their higher-ups. This is in addition to other aspects such as the addition and development of our local database using MongoDB. This is just a few of what we have done.

What we will do to remedy this confusion. Is that we will add the following for starters:
- We will add some more supporting information to the landing page that details where you can find the output for the project. This could include some of the major outputs from the project, and perhaps some images.
- Another item that could be added is to edit the README.md file that is located in the output folder. This could be modified to provide links to important areas of the repository to show the output of the project. We could also detail further in the README.md that the output shown there is not every piece of output, but just the major outputs that we deem are important enough to report there.
- Another aspect that could be useful is to add labels to issues that are being completed or have been completed in this semester. To show that these are worked on this semester and show the output better.

For updates see Issue #107.

These are all the questions that we got asked in the audit and we will make sure to work on and develop our project to reflect this feedback and work towards the end of the semester.

**Comment by Edward-Nivison** [comment]
_The outputs are very useful and indicate a working system is very likely the result of the project. Having more detail on the constraints and rankings for the algorithm used would be useful to confirm the priorities are being met._

We are working on the documentation and will provide some developer documentation to detail what is happening in the backend so people who are curious can understand what all the criteria and their rankings are.

**Comment by Edward-Nivison** [comment]
_The output lab allocation app is very useful and satisfies the basic need of the university administration team. They have provided valuable output for the clients. Only possible improvement is that, the presentation does not show how the application handles the situation if a large number of students quit one course and join others; maybe, a manual allocation method could be considered as the backup to handle such risks._

We are providing the algorithm to allocate lab rooms according to numbers like the number of students, but what we are mainly providing is the ease of generating all of the lab room allocations in the shortest time possible making the School of Computing staff have a layout for the timetable a lot quicker. We have the alterations that can be made such as moving classes around, the ability to add new criteria to the fitness function for new requirements which kind of cover that occurence with the duplicate classes running at the same time, so if both run down on students, they can be combined.

**Comment by Edward-Nivison** [comment]
_Nice work on such a beautiful demo, team! One thing you could improve on is that, in your presentation, you didn’t explicitly mention which functions were completed this semester, even though you showed your deliverables. This could cause some confusion for your stakeholders (shadow team, tutors, and examiner). It would be best if you could emphasize that._

Thanks! What we have been working on has been to do just that. I have already made a project output section on the landing page detailing some things that we have done which links to a folder where we can detail some major developments in markdown files and with images. Another thing from this reflection is that I have added the sem 2 label to the issues made and finished this semester for easier viewing. The best way is to use the github issues to see what is being done, and the projects page as well. You can see Issue #107 .

**Comment by Edward-Nivison** [comment]
_Set deadlines for each assignment_

I am not completely sure what is coming from this feedback. From one stance, it is add the deadlines of audits and stuff to our timeline, which is fair, but the project is more focused on the deliverables for the project and we have our own timeline for ourselves separate. We communicate in meetings about audits, and deliverables in that sense.

For the other end, you can see our deliverables on the landing page, as well as in the statement of work, through the github issues, and probably the best, through the projects in github itself, we have a standup and a roadmap there with the live issues and their deadlines detailed there.

**Comment by Edward-Nivison** [comment]
_teams actions and decisions are clear and we are communicating clearly to make decisions. i think more team members should be voicing opinions when making decisions._

I agree, it should be a team effort, but what does happen though (that isn't shown very well at the moment) is that we make most of our decisions as a team, during our meetings, and one person usually writes them down. So even though it is one person writing it usually, it is the team making the decision. Perhaps that could be improved on in our practice of doing things.

@RachelCaoCC is that a field that we can do? Adding who came up with the decision?

#93

**Comment by Edward-Nivison** [comment]
_Include every stakeholder in the process_

We should be working soon on some more user testing, and we can expand our user testing to the shadow team as well. That is our plan, when we get something that can be used more than a couple times (due to firebase limitations of pulling and pushing), however we are very close to that reality.

#96

**Comment by Edward-Nivison** [comment]
_Our decision making documentation has been much improved since last semester. We need to ensure we go back and refer to the decisions we record, to ensure we reflect on them and the client is informed._

That is very important, I am going to add that as something we should do every team meeting. We will just get everyone to read through them and make any comments that we feel should be made. Thanks!

**Comment by Edward-Nivison** [comment]
_We are working well, however we should try and use the github issues and roadmap a bit more effectively, assign yourself to some issues and set deadlines._

This is communicated with the team very clearly, and we have been pushing it all semester, it is up to the team members to do this, and there are several supporting documents for that too. You can find those [here](https://github.com/mazfil/lab-allocator/blob/main/docs/development/development-checklist.md)

**Comment by Edward-Nivison** [comment]
_Team seems to be working well, the only improvement would be to have at least one whole team meeting every 4-6 weeks so that I can see all Team members, but the information provided to the Project lead and others is being included and questions are responded to._

_Team working sufficiently. But i dont think the team is working consistently together to achieve the goals. I think more people need to work together to actually complete tasks_

I will stress more to the team about attendance to meetings so we can all be there, There is a always a consistent amount of people being there, but some have unavoidable absences. 

Working as a team is paramount, that is why I have been pushing for user documentation, and I think we have been doing pretty well at it, we just need to delegate tasks to people and say for them to do it. Give some responsibility.

**Comment by Edward-Nivison** [comment]
_I didn't find specific project task division or other content related to team work. But according to the audit pre 2, their teamwork should be good._

That is a fair point to bring up. I forgot that we should be showing that more clearly. What we have for that is the assigning of issues and our own "we know who is doing what" kind of attitude, but that should be done more clearly and show what each team members role is, and what they are currently working on. Thanks for the feedback!

**Comment by Edward-Nivison** [comment]
> _I didn't find specific project task division or other content related to team work. But according to the audit pre 2, their teamwork should be good._
> 
> That is a fair point to bring up. I forgot that we should be showing that more clearly. What we have for that is the assigning of issues and our own "we know who is doing what" kind of attitude, but that should be done more clearly and show what each team members role is, and what they are currently working on. Thanks for the feedback!

Another good piece of feedback to this.

_The team meeting records have shown how they distribute tasks based on each person's specialisation. It would be better if they include each person's specialisation and skill set as the supporting material for each task allocation._

**Comment by Edward-Nivison** [comment]
> _Team seems to be working well, the only improvement would be to have at least one whole team meeting every 4-6 weeks so that I can see all Team members, but the information provided to the Project lead and others is being included and questions are responded to._
> 
> _Team working sufficiently. But i dont think the team is working consistently together to achieve the goals. I think more people need to work together to actually complete tasks_
> 
> I will stress more to the team about attendance to meetings so we can all be there, There is a always a consistent amount of people being there, but some have unavoidable absences.
> 
> Working as a team is paramount, that is why I have been pushing for user documentation, and I think we have been doing pretty well at it, we just need to delegate tasks to people and say for them to do it. Give some responsibility.

Another piece of feedback regarding the allocation of team work, we will work together in the team meetings to go over that, and make sure that everyone is given something to do, and that they can complete it in a reason timeline.

_The team is mainly working well to achieve goals, with most of the team contributing well. We need to ensure that we continue to equally distribute the workload - we should ensure in each meeting we decide what is to be worked on by everything in the following week._

**Comment by Edward-Nivison** [comment]
_We have been communicating weekly with the client and on-the-know basis when there is an important decision to get comments on. What we should do is give our client some agenda items ahead of the meeting if we need something from them at the meeting._

A piece of feedback regarding to give some agenda to the client, if we need to source anything from them, such as test data, feedback for something, or getting some stakeholders available to join ahead of time.

@mazfil and @sineeha-Kodwani. This would be good as spokespeople to make note of.

**Comment by Edward-Nivison** [comment]
> _We have been communicating weekly with the client and on-the-know basis when there is an important decision to get comments on. What we should do is give our client some agenda items ahead of the meeting if we need something from them at the meeting._
> 
> A piece of feedback regarding to give some agenda to the client, if we need to source anything from them, such as test data, feedback for something, or getting some stakeholders available to join ahead of time.
> 
> @mazfil and @sineeha-Kodwani. This would be good as spokespeople to make note of.

Well the next feedback contradicts this.

_Communications with stakeholders shouldnt just be limited to spokespeople. Spokespeople are contacts between techlauncher staff and the team. Other team members are able to communicate with stakeholders when spokespeople are unnavailable._

We are happy to do communication if people are not available to communicate with people too. It should just be noted though, that we should be keeping an up-to-date communication log with relevant stakeholders then, so we know what has been communicated and what hasn't. Or cc in your communications with us so we can be in the loop.

**Comment by Edward-Nivison** [comment]
_The SoCo team demonstrated productive and coherent engagement with the stakeholders, including team members, clients and tutors. They used prepared agenda to show what they would ask the clients and tutors. One small piece of possible improvement is that they can include specific questions that individual team members would ask in the client meeting agendas._

Good idea, this corresponds to the client agenda being made before the client meetings, it is a good idea to do this, as everyone should be able to have something that can ask. I ask for people's input on the agenda each week so they have the opportunity to add them then.

**Comment by Edward-Nivison** [comment]
_Our stakeholder engagement is good - we have been in contact with other SoCo members for user testing and meet with our client most weeks. We should start engaging more with the stakeholders about the backend too._

Perhaps we can look at talking with the School of Computing Facility team such as Bob or Ashleigh. They are continuing the upkeep of the product from my understanding in the future, so it could be good to explain the project to them, and get some feedback.

#96

**Comment by Edward-Nivison** [comment]
_The team could probably do a more in-depth analysis of advice/comments received to understand areas of improvement and develop a deeper reflection as to where improvements need to be made (brief reflections are made without thorough and in-depth analysis)._

This is a very good point. What I have done is made it mandatory to go over reflections and decisions in the team meetings. This should evolve our reflection and we should document that through the meeting minutes, but also then develop them further into a meaningful issue or markdown file that we can reference back to.

**Comment by Edward-Nivison** [comment]
_The team is making regular reflections and recording them. We need to ensure that we go back and refer to reflections we make so we can use it to improve our team further._

Another reference to the going back to reflections, I have made it mandatory in the team meetings to go over the reflections and decisions, so we can make a more detailed reflection on the reflections already made.

**Comment by RachelCaoCC** [comment]
_teams actions and decisions are clear and we are communicating clearly to make decisions. i think more team members should be voicing opinions when making decisions._

A column has been added regards who is making decision in decision Log.

**Comment by Edward-Nivison** [comment]
Closing this issue as semester is finished, you can reopen this issue for future projects!
