### ISSUE TITLE
Decision Logs

### ISSUE THREAD

**Issue by Edward-Nivison** [mazfil/lab-allocator#93]
When you are making a decision, you can reference this issue over the semester in your commits, pull requests, comments. Wherever you see fit so that we can add the decision logs properly!

The structure for decision logs at the current moment is:

|Decision|Outcome|Responsible Party|Decision Date|Status|
|--|--|--|--|--|
|Our client wants for distinctive colouring when viewing the timetable|We are working on filtering that will show what the user would like to see most prominently.|Frontend team|DD/MM/YYYY|In-Progress|

This is an example, if you want to add your decision yourself to the decision log, it is located in `laballocator/docs/Decision-log.md`.

Thanks!

**Comment by Edward-Nivison** [comment]
We have made the decision to also start testing on the development side, ahead of schedule to ensure that the product is working as intended and can produce what we are wanting it to produce. This is seen in issue #95

**Comment by Edward-Nivison** [comment]
We have made a decision to detail any important output that we should be showing to the audit in the [Project Output](https://github.com/mazfil/lab-allocator/tree/main/docs/output). It isn't everything, as that would be impossible and ineffective use of our time, however it will show major points in our delivery to the client, team and project.

**Comment by RachelCaoCC** [comment]
There is some duplicates in Decision Log sheet and decision-log.md. will do some merge to sort this up.

**Comment by RachelCaoCC** [comment]
The format in google doc and decision-log.md should match. Google doc format was using plain text, I changed the to drop down chips for clearer label.

**Comment by RachelCaoCC** [comment]
<img width="615" alt="Screenshot 2024-08-26 at 11 37 51 PM" src="https://github.com/user-attachments/assets/1d022773-3446-4059-964d-806fecdb751b">
We can use drop down to assign responsible part and decision type now.

**Comment by RachelCaoCC** [comment]
Merge Decision Log and Decision Log(sheets).
Decision Log link is wrong and I put google doc in Decision Log.md

**Comment by RachelCaoCC** [comment]
I am currently adding issue related to each decision. It will be good if everyone can check keep down decision is made by whom as @Edward-Nivison mentioned in last meeting

**Comment by Edward-Nivison** [comment]
Closing this issue as semester is finished, you can reopen this issue for future projects!
